name: FoD SAST scan                                     # Name of this workflow
on:
  push:                                                 # Perform Fortify SAST on push and/or pull requests
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:                                                  
  build:
    runs-on: ubuntu-latest                              # Use the appropriate runner for building your source code

    steps:
      - uses: actions/checkout@v2                       # Check out source code
      - uses: actions/setup-java@v1                     # Set up Java 1.8; required by ScanCentral Client and FoD Uploader
        with:
          java-version: 1.8

      ### Set up ScanCentral Client and FoD Uploader ###
      - uses: fortify/gha-setup-scancentral-client@v1   # Set up ScanCentral Client and add to system path
      - uses: fortify/gha-setup-fod-uploader@v1         # Set up FoD Uploader, set FOD_UPLOAD_JAR variable

      ### Package source code using ScanCentral Client ###
      - run: scancentral package -bt mvn -o package.zip

      ### Start Fortify on Demand SAST scan ###
      - run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl https://api.ams.fortify.com/ -purl https://ams.fortify.com/ -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" -ep 2 -pp 1
        env:                                            
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }} 

      ### Archive ScanCentral logs and package ###
      - uses: actions/upload-artifact@v2                # Archive ScanCentral logs for debugging purposes
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log
      - uses: actions/upload-artifact@v2                # Archive ScanCentral package for debugging purposes
        if: always()
        with:
          name: package
          path: package.zip
